// Regenerates lib/jd.ts from the two JD .docx files.
// Usage: node scripts/import-jds.mjs "<path to PM jd.docx>" "<path to SPM jd.docx>"
import { writeFileSync } from "node:fs";
import mammoth from "mammoth";

const [pmPath, spmPath] = process.argv.slice(2);
const read = async (p) => (await mammoth.extractRawText({ path: p })).value.replace(/\n{2,}/g, "\n").replace(/[ \t]+/g, " ").trim();
const pm = await read(pmPath);
const spm = await read(spmPath);

writeFileSync(
  "lib/jd.ts",
  `import type { Role } from "./types";

// Job descriptions: BACKGROUND ONLY, for writing interview briefs and emails.
// Candidates are NEVER scored against these. Scoring uses rubric_criteria only.
// Generated by scripts/import-jds.mjs from MESA_Kargo_JD_Product Manager.docx and MESA_Kargo_JD_Senior Product Manager.docx.
export const JOB_DESCRIPTIONS: Record<Role, string> = {
  PM: ${JSON.stringify(pm)},
  SPM: ${JSON.stringify(spm)},
};
`,
);
console.log(`lib/jd.ts written (PM ${pm.length} chars, SPM ${spm.length} chars)`);
